# Generated by Django 4.2.20 on 2026-05-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(default='Main Office', max_length=200)),
                ('office_latitude', models.FloatField()),
                ('office_longitude', models.FloatField()),
                ('radius_meters', models.PositiveIntegerField(default=100)),
                ('allowed_wifi_cidrs', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
